version: '3'

services:
    database:
        image: postgres:9.4-alpine
        ports:
        - 5432:5432
        environment:
          POSTGRES_USER: diablo2
          POSTGRES_PASSWORD: diablo2
        volumes:
        - ./sql/diablo2-filled.sql:/docker-entrypoint-initdb.d/init.sql

    frontend:
        build: ci/frontend
        expose:
        - 80
        ports:
        - 80:80
        volumes:
        - ./www:/var/www/html
        - ./templates:/templates
        links:
        - database:database
